# 2.1 if, for, while

## if 문
- if ~ elif ~ else
- 인덴트 주의

In [2]:
score = 72

if score >= 90 :
    print("A 학점")
    print("good job!!!")
elif score >= 80 :
    print('B 학점')
    print('분발합시다~')
elif score >= 70 :
    print('C 학점')
    print('공부하자..')
else :
    print('D 학점')
    print('TnT')

C 학점
공부하자..


## for 문

In [3]:
subjects = ['korean','science','math','english']

for n in subjects :
    print(n)

korean
science
math
english


### break : 반복문을 멈추고 밖으로 나가라는 의미의 키워드
- if, for, while 에서 모두 사용됨


In [8]:
for n in subjects :
    if n == 'math' :
        break
    print(n)

print('\n>>> english 수행되지 않음')

korean
science

>>> english 수행되지 않음


### continue : 가던 길을 멈추고 다음 길로 계속 가야 함을 의미 != break

In [9]:
for n in subjects :
    if n == 'math' :
        continue
    print(n)
    
print('\n>>> english 수행')

korean
science
english

>>> english 수행


## while 문
- 조건을 만족하면 무한히 반복해 내용 처리
- 조건이 만족하지 않게 하거나, 반복을 종료시켜야 하는 별도의 조건 필요할 수 있음 주의

In [10]:
num = 0

while num < 10 :
    num += 1
    print(num)

1
2
3
4
5
6
7
8
9
10


### while 문에서도 if 문과 비슷하게 else 문 사용 가능
- while 문의 조건식이 틀리면 최종적으로 else 문 수행 내용 실행

In [11]:
num = 0

while num < 10 :
    num += 1
    print(num)
else :
    print("끝")

1
2
3
4
5
6
7
8
9
10
끝


In [12]:
num = 0

while num < 10 :
    num += 1
    print(num)
print("끝")

1
2
3
4
5
6
7
8
9
10
끝


## function

### 01. 내장 함수
- print() : 화면 출력
- type()  : 데이터나 변수의 데이터타입 반환
- int()   : 정수형 데이터 타입으로 변환
- float() : 실수형 데이터 타입으로 변환
- str()   : 문자열 데이터 타입으로 변환
- sum()   : 값들의 합계 반환
- len()   : 길이 구하기
- list()  : 새로운 리스트 데이터 타입 생성
- tuple() : 새로운 튜플 데이터 타입 생성
- dict()  : 새로운 딕셔너리 데이터 타입 생성
- round() : 반올림 값 구하기
- max()   : 최대값 구하기
- min()   : 최소값 구하기
- abs()   : 절대값 구하기

### 02. 외장 함수
- import 사용

In [13]:
import random
random.random()

0.7551327162762964

### 03. 사용자 정의 함수
- def 키워드 사용

1. 매개변수가 없는 경우 함수만 호출하면 일정 값만 출력됨

In [14]:
def who() :
    print("it's me !")

In [16]:
who()  # 매개변수(입력값) 없이 사용

it's me !


2. return 없이 print 만 있는 경우 : 변수값에 저장되지 않음

In [18]:
def my_sqrt(num) :
    print( num * num )

In [19]:
my_sqrt(10)

100


In [20]:
tmp_ = my_sqrt(10)

100


In [21]:
tmp_ # 출력값 없음

3. return 으로 내뱉는 값 설정하여 변수에 값 할당해보기

In [22]:
def cubed(num) :
    return num*num*num

In [23]:
cubed(5)

125

In [24]:
tmp_ = cubed(5)

In [25]:
tmp_

125

# 2.2 library

- pandas, numpy, sklearn

## 01. pandas

- 행과 열로 구성된 1차원, 2차원의 데이터를 다룸

In [26]:
import pandas as pd

### pandas 데이터 타입 : Series, DataFrame

In [30]:
lst_var = ['홍길동', '이순신', '유관순', '윤봉길']
series_ = pd.Series(lst_var)

print(type(series_))
display(series_)

<class 'pandas.core.series.Series'>


0    홍길동
1    이순신
2    유관순
3    윤봉길
dtype: object

In [29]:
lst_var = (['홍길동',29,'여'],
           ['이순신',24,'남'],
           ['유관순',38,'남'],
           ['윤봉길',31,'여'])

# list를 데이터 프레임 타입으로 변경
df_ = pd.DataFrame(lst_var)

print(type(df_))
display(df_)

<class 'pandas.core.frame.DataFrame'>


0   1  2
0  홍길동  29  여
1  이순신  24  남
2  유관순  38  남
3  윤봉길  31  여

### index, columns 변경

In [31]:
df_.index = ['1번','2번','3번','4번']
df_

0   1  2
1번  홍길동  29  여
2번  이순신  24  남
3번  유관순  38  남
4번  윤봉길  31  여

In [32]:
df_.columns = ['이름','나이','성별']
df_

이름  나이 성별
1번  홍길동  29  여
2번  이순신  24  남
3번  유관순  38  남
4번  윤봉길  31  여

### 일부 열/행 값 추출 : [ ]

In [33]:
# 열 값 추출
df_['나이']

1번    29
2번    24
3번    38
4번    31
Name: 나이, dtype: int64

행 값 추출시,
- index num의 경우 : [시작위치:끝위치+1]
- index name 의 경우 : [시작위치:끝위치]

In [34]:
# 행 값 추출
df_[1:3]

이름  나이 성별
2번  이순신  24  남
3번  유관순  38  남

In [35]:
df_['2번':'3번']

이름  나이 성별
2번  이순신  24  남
3번  유관순  38  남

### 파일 읽고 쓰기
- pd.read_csv(), pd.to_csv()

In [ ]:
# 코드 예시로 실행은 X

dataset = pd.read_csv('data/train.csv')
dataset

In [ ]:
# 코드 예시로 실행은 X

dataset.to_csv('data/12345.csv')

## 02. sklearn

- 머신러닝(기계학습) 수행할 수 있는 라이브러리
- scikit-learn 의 약자

### sklearn 라이브러리/ 패키지
- preprocessing : StandardScaler, MinMaxScaler, RobustScaler, OneHotEncoder, LabelEncoder, ...
- model_selection : train_test_split, cross_validation, learning_curve, validation_curve, GridSearchCV, ...
- linear_model : LogisticRegression, Perceptron, ...
- tree : DecisionTreeClassifier, ...

In [37]:
# 함수 import
from sklearn.model_selection import train_test_split
from sklearn.tree            import DecisionTreeClassifier

## 03. numpy

- 벡터, 행렬 등 수치 연산 수행하는 선형대수 라이브러리

In [39]:
import numpy as np

np.zeros((2,3))      # 2행 3열 모두 0으로 채우기

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.ones((2,3))       # 2행 3열 모두 1로 채우기

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.full((2,3), 10)   # 2행 3열 특정 수(10)로 채우기

array([[10, 10, 10],
       [10, 10, 10]])

In [50]:
np.array(range(20))  # 0부터 20개의 숫자 만들기 > shape : (20, )

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [52]:
np.array(range(20)).reshape(4,5)   # 0부터 20개의 숫자로 4행 5열의 행렬 만들기

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 2.3 내장 함수 활용

In [55]:
data = {
    '나이' : [20, 23, 49, 38, 32, 29, 25, 30, 32, 26],
    '성별' : ['male','female','male','female','female','female','female','female','male', np.nan]
       }

In [56]:
data_frm = pd.DataFrame(data)
data_frm

나이      성별
0  20    male
1  23  female
2  49    male
3  38  female
4  32  female
5  29  female
6  25  female
7  30  female
8  32    male
9  26     NaN

## 숫자 계산 함수

### - 합계 : sum()

In [57]:
data_frm['나이']

0    20
1    23
2    49
3    38
4    32
5    29
6    25
7    30
8    32
9    26
Name: 나이, dtype: int64

In [58]:
data_frm['나이'].sum()

304

In [59]:
sum(data_frm['나이'])

304

### - 최대값 : max()

In [61]:
data_frm['나이'].max()

49

In [62]:
max(data_frm['나이'])

49

### - 최소값 : min()

In [63]:
data_frm['나이'].min()

20

In [64]:
min(data_frm['나이'])

20

### - 평균 : mean()

In [65]:
data_frm['나이'].mean()

30.4

In [67]:
# mean(data_frm['나이']) -- error

### - 중위값 : median()

In [68]:
data_frm['나이'].median()

29.5

### - 분산 : var()

In [69]:
data_frm['나이'].var()

69.15555555555557

### - 표준편차 : std()

In [70]:
data_frm['나이'].std()

8.315981935740094

### - 거듭제곱 : pow()
- 숫자 데이터의 지수값 즉, 거듭제곱값 계산

In [71]:
pow(data_frm['나이'], 3)

0      8000
1     12167
2    117649
3     54872
4     32768
5     24389
6     15625
7     27000
8     32768
9     17576
Name: 나이, dtype: int64

### - 사분위수 : quentile()

In [73]:
data_frm.quantile(.25)   # 1사분위수

나이    25.25
Name: 0.25, dtype: float64

In [74]:
data_frm.quantile(.5)   # 2사분위수

나이    29.5
Name: 0.5, dtype: float64

In [75]:
data_frm.quantile(.75)   # 3사분위수

나이    32.0
Name: 0.75, dtype: float64

In [76]:
data_frm.quantile(1)     # 4사분위수

나이    49.0
Name: 1.0, dtype: float64

### - 반올림 구하기 : round()

In [79]:
round(data_frm['나이'] / 7)  # default : 소수점 첫째 자리에서 반올림

0    3.0
1    3.0
2    7.0
3    5.0
4    5.0
5    4.0
6    4.0
7    4.0
8    5.0
9    4.0
Name: 나이, dtype: float64

In [80]:
round(data_frm['나이'] / 7, 2)

0    2.86
1    3.29
2    7.00
3    5.43
4    4.57
5    4.14
6    3.57
7    4.29
8    4.57
9    3.71
Name: 나이, dtype: float64

In [83]:
import math

print('ceil  : ', math.ceil(123.456))
print('floor : ', math.floor(123.456))

ceil  :  124
floor :  123


## shape 관련 함수

### - 모양 구하기 : shape
- 괄호 없이 DataFrame.shape 으로 사용

In [85]:
data_frm.shape, data_frm['나이'].shape

((10, 2), (10,))

### - 길이 구하기 : len( )

In [91]:
print('데이터프레임 - 원소개수 : ', len(data_frm))
print('문자열 - 문자개수(길이) : ', len('Superman'))
print('문자열 - 문자개수(길이) : ', len('1234567890'))
# print('숫자 - 길이             : ', len(123)) -- error

데이터프레임 - 원소개수 :  10
문자열 - 문자개수(길이) :  8
문자열 - 문자개수(길이) :  10


### - 크기 구하기 : size
- 데이터 변수 안에 들어 있는 값들의 개수 출력

In [92]:
data_frm.size

20

### - 상위 데이터 가져오기 : head( )

In [93]:
data_frm.head()

나이      성별
0  20    male
1  23  female
2  49    male
3  38  female
4  32  female

In [94]:
data_frm.head(2)

나이      성별
0  20    male
1  23  female

### - 하위 데이터 가져오기 : tail( )

In [95]:
data_frm.tail()

나이      성별
5  29  female
6  25  female
7  30  female
8  32    male
9  26     NaN

In [96]:
data_frm.tail(2)

나이    성별
8  32  male
9  26   NaN

### - 열 이름 구하기 : columns

In [97]:
data_frm.columns

Index(['나이', '성별'], dtype='object')

### - 행 이름 구하기 : index

In [98]:
data_frm.index

RangeIndex(start=0, stop=10, step=1)

## 데이터 요약 관련 함수

### - 값의 개수 세기 : value_counts( )

In [100]:
data_frm['성별'].value_counts()

female    6
male      3
Name: 성별, dtype: int64

### - 중복 제거하기 : unique( )

In [101]:
data_frm['성별'].unique()

array(['male', 'female', nan], dtype=object)

### - null 여부 확인하기 : isnull( )

In [102]:
data_frm.isnull()

나이     성별
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False
5  False  False
6  False  False
7  False  False
8  False  False
9  False   True

In [103]:
data_frm['성별'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: 성별, dtype: bool

In [104]:
sum(data_frm['성별'].isnull())  # 성별 데이터의 null 개수 세기

1

### - 개수 세기 : count( )

In [106]:
data_frm.count()   # data_frm 의 열별 값의 개수 세기 > null 값은 count 에 포함되지 않음

나이    10
성별     9
dtype: int64

In [107]:
'I am Superman!'.count('a')

2

### - 정보 조회하기 : info( )

In [108]:
data_frm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   나이      10 non-null     int64 
 1   성별      9 non-null      object
dtypes: int64(1), object(1)
memory usage: 288.0+ bytes
